### ISSUE TITLE
"PermissionError: [Errno 13] Permission denied" thrown during building

### ISSUE THREAD

**Issue by sidney-simmons** [sidney-simmons/gradle-plugin-docker#27]
The following error is occurring when running "dockerComposeBuild".

```
> Task :dockerComposeBuild FAILED
postgres uses an image, skipping
Building boot
[10072] Failed to execute script docker-compose
Traceback (most recent call last):
File "site-packages\docker\utils\build.py", line 97, in create_archive
File "tarfile.py", line 1980, in addfile
File "tarfile.py", line 255, in copyfileobj
PermissionError: [Errno 13] Permission denied
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "docker-compose", line 6, in <module>
File "compose\cli\main.py", line 71, in main
File "compose\cli\main.py", line 127, in perform_command
File "compose\cli\main.py", line 287, in build
File "compose\project.py", line 386, in build
File "compose\project.py", line 368, in build_service
File "compose\service.py", line 1084, in build
File "site-packages\docker\api\build.py", line 159, in build
File "site-packages\docker\utils\build.py", line 31, in tar
File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\C:\Users\sassi\git\simple-postgres\.gradle\5.4.1\executionHistory\executionHistory.lock
```

**Comment by sidney-simmons** [comment]
It looks like this is caused when docker tries to copy the entire context into the new image.  Some of the files in the project's /.gradle directory have locks on them and therefore can't be copied.  To fix this you need to exclude the /.gradle directory from being copied into the image by adding it to a .dockerignore file.  The content should look like this...

```
# Ignore Gradle project-specific cache directory
.gradle
```
